In [81]:
#

# Janela Movel (Moving Windows Statistics)

#

In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [62]:
dado_v = np.array([[81,77,103,112,123,19,40,111,114,120],[82,61,110,121,119,77,52,111,117,124],[82,74,97,105,112,91,73,115,118,129],[88,70,103,111,122,64,84,105,113,123],[89,88,94,110,116,108,73,107,118,127],[77,82,86,101,109,113,79,102,120,121],[74,80,85,90,97,101,96,72,128,130],[75,80,83,87,94,99,95,48,139,145],[77,84,74,108,121,143,91,52,136,144],[87,100,47,111,124,109,0,98,134,144]],float)

v = np.reshape(dado_v,(1,100))
V = np.squeeze(v)



print dado_v
print ""
print dado_v[0,1]



[[  81.   77.  103.  112.  123.   19.   40.  111.  114.  120.]
 [  82.   61.  110.  121.  119.   77.   52.  111.  117.  124.]
 [  82.   74.   97.  105.  112.   91.   73.  115.  118.  129.]
 [  88.   70.  103.  111.  122.   64.   84.  105.  113.  123.]
 [  89.   88.   94.  110.  116.  108.   73.  107.  118.  127.]
 [  77.   82.   86.  101.  109.  113.   79.  102.  120.  121.]
 [  74.   80.   85.   90.   97.  101.   96.   72.  128.  130.]
 [  75.   80.   83.   87.   94.   99.   95.   48.  139.  145.]
 [  77.   84.   74.  108.  121.  143.   91.   52.  136.  144.]
 [  87.  100.   47.  111.  124.  109.    0.   98.  134.  144.]]

77.0


In [10]:
# definindo valores:

a  = 4 # a dimensao do retangulo em x
b  = 2 # a dimensao do retangulo em y

px = 2 # quanto anda o retangulo na direcao x
py = 1 # quanto anda o retangulo na direcao y


dim = dado_v.shape
dim_x = dim[0] # valores do eixo x de v
dim_y = dim[1] # valores do eixo y de v

K = 1+(dim_x - a)/px
L = 1+(dim_y - b)/py

print K,"valor do eixo x" # define o loop k 
print L,"valor do eixo y" # define o loop l


4 valor do eixo x
9 valor do eixo y


In [77]:
# programa MWS para médias
rmv = np.array([[0]*K]*L,float)
mv  = []


for l in range (L):
    for k in range (K):
        for j in range (b):
            for i in range (a):
                
                mv.append(dado_v[j+(l*py),i+(k*px)])
        rmv[l,k] = np.mean(mv)
        mv = []
print "medias"
print rmv

[[  93.375   98.      81.5     98.625]
 [  91.5    104.      93.75   104.875]
 [  91.25   100.625   95.75   107.5  ]
 [  94.125  103.5     97.375  106.25 ]
 [  90.875  104.625  100.875  105.875]
 [  84.375   97.75    96.125  106.   ]
 [  81.75    92.      87.75   106.625]
 [  83.5    101.125   92.875  106.25 ]
 [  86.     104.625   92.25    99.875]]


In [78]:
rstdv = np.array([[0]*K]*L,float)
stdv  = []


for l in range (L):
    for k in range (K):
        for j in range (b):
            for i in range (a):
                
                mv.append(dado_v[j+(l*py),i+(k*px)])
        rstdv[l,k] = np.std(mv)
        stdv = []
print "desvio padrao"
print rstdv

[[ 19.61464695  27.16320754  31.79816447  31.72710789]
 [ 29.608107    27.94861356  27.2813899   27.29106979]
 [ 26.19475006  25.44135413  24.97191604  24.69331858]
 [ 23.99637662  23.62559894  23.38441433  23.17595737]
 [ 22.66766514  22.20879803  21.89861013  21.82698659]
 [ 21.57262345  21.17638486  20.89388302  20.96151194]
 [ 20.80542958  20.46337967  20.42783141  21.05571779]
 [ 20.92178286  20.93915624  21.28684867  22.06875928]
 [ 22.07555447  22.32830492  23.19347529  24.25382963]]
